### NUMPY

In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
a=np.array([10,20,30,50,60,0])
a

array([10, 20, 30, 50, 60,  0])

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(6,)

In [5]:
a.ndim

1

In [6]:
a.size

6

In [7]:
a[0]

10

In [8]:
a[2]

30

### multi dimensional array

In [9]:
d=np.array([[10,20,30,],[23,55,15]])
d

array([[10, 20, 30],
       [23, 55, 15]])

In [10]:
for i in d:
    print(i)

[10 20 30]
[23 55 15]


In [11]:
d.shape

(2, 3)

In [12]:
d.dtype

dtype('int32')

In [13]:
d.ndim

2

In [14]:
d.size

6

###  multi dimension

In [15]:
a=np.array([[[[1,2,3,4,]]]])
a

array([[[[1, 2, 3, 4]]]])

In [16]:
a.ndim

4

In [17]:
a=np.array([[[[[[1,50,25,60,89],[5,3,20,52,30,52,50,],[50,54,65,85,52,]]]]]])
a

array([[[[[list([1, 50, 25, 60, 89]),
           list([5, 3, 20, 52, 30, 52, 50]),
           list([50, 54, 65, 85, 52])]]]]], dtype=object)

In [18]:
a.ndim

5

In [19]:
c=np.array([
[
[10,20,30,40],[8,8,2,1],[1,1,1,2]
],
[
[9,9,2,39],[1,2,3,3],[0,0,3,2]
],
[
[12,33,22,1],[22,1,22,0],[0,2,3,1]
]
],dtype =float)

c


array([[[10., 20., 30., 40.],
        [ 8.,  8.,  2.,  1.],
        [ 1.,  1.,  1.,  2.]],

       [[ 9.,  9.,  2., 39.],
        [ 1.,  2.,  3.,  3.],
        [ 0.,  0.,  3.,  2.]],

       [[12., 33., 22.,  1.],
        [22.,  1., 22.,  0.],
        [ 0.,  2.,  3.,  1.]]])

In [20]:
c.shape

(3, 3, 4)

In [21]:
c.ndim

3

In [22]:
c.size

36

In [24]:
c[1][2]

array([0., 0., 3., 2.])

In [25]:
c[0][0][2]

30.0

In [27]:
c[2][0][0]

12.0

### filling array

In [29]:
v=np.full((3,5,4),7)
v

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

### zero and ones

In [45]:
s=np.ones((5,10,10))
s

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

In [39]:
m=np.zeros((10,2,10))
m

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.,

### empty and random

In [52]:
p=np.empty((1,1))
p

array([[0.80913815]])

In [51]:
h=np.random.random((2,2))
h

array([[0.0131533 , 0.41913543],
       [0.42744151, 0.80913815]])

In [59]:
h.ndim,h.size

(2, 4)

### range

In [62]:
e= np.arange(10,100,2)
e

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [64]:
for i in range(10,100,2):
    print(i)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


### linspace

In [70]:
v=np.linspace(0,50,7)
v

array([ 0.        ,  8.33333333, 16.66666667, 25.        , 33.33333333,
       41.66666667, 50.        ])

In [71]:
v.size

7

In [72]:
v.shape

(7,)